name: Generate Clean Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prep folder structure
        run: |
          mkdir diam_AAALoadingTips
          find . -maxdepth 1 ! -name '.' ! -name '..' ! -name '.git' ! -name '.github' ! -name 'diam_AAALoadingTips' -exec mv {} diam_AAALoadingTips/ \;
          
          rm -rf diam_AAALoadingTips/_previewimage
          rm -rf diam_AAALoadingTips/README.md
          rm -rf diam_AAALoadingTips/LICENSE
          rm -rf diam_AAALoadingTips/.gitignore
          rm -rf diam_AAALoadingTips/.gitattributes

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'diam_AAALoadingTips-${{ github.ref_name }}.zip'
          path: 'diam_AAALoadingTips'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "diam_AAALoadingTips-${{ github.ref_name }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
