name: Generate Clean Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'MyGameMod-${{ github.ref_name }}.zip'
          exclusions: '*.git* /*.gitignore README.md LICENSE'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "MyGameMod-${{ github.ref_name }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
